# Docker
- task: CmdLine@2
  inputs:
    script: |
      sudo git clone https://github.com/samzri1/brief14.git
      cd /
      cd brief14
      sudo docker build -t img_app_py .
      sudo docker tag img_app_py:latest lyllabani/img_app_py:latest
      sudo docker login -u lyllabani -p dckr_pat_BPdule2UQ-Mif_zdZGq6E5R24EA
      sudo docker push lyllabani/img_app_py:latest
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/image/dockerfile'
        tags: |
          $(tag)
